FROM golang:alpine AS build
WORKDIR /borg/tools/droid
COPY . ./
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o droidapi cmd/droid_api.go

FROM alpine:3.18 AS prod
WORKDIR /borg/tools/droid
COPY --from=build /borg/tools/droid/ .
RUN apk update
RUN apk add unzip openjdk17
RUN unzip bin/droid-binary-6.7.0-bin.zip -d bin/
RUN chmod +x bin/droid.sh
CMD ["./droidapi"]