FROM golang:alpine AS build
WORKDIR /borg/tools/droid
COPY . ./
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o droidapi cmd/droid-api.go

FROM alpine:3.18 AS prod
WORKDIR /borg/tools/droid
COPY --from=build /borg/tools/droid/ .
RUN apk update
RUN apk add unzip openjdk11
RUN unzip bin/droid-binary-6.7.0-bin.zip
RUN chmod +x bin/droid-binary-6.7.0-bin/droid.sh
CMD ["./droidapi"]