FROM golang:1.21.3-alpine3.18

RUN apk update
RUN apk add unzip openjdk11
WORKDIR /borg/tools/droid
COPY . ./
RUN unzip bin/droid-binary-6.7.0-bin.zip
RUN chmod +x bin/droid-binary-6.7.0-bin/droid.sh
CMD ["go", "run", "cmd/droid-api.go"]