services:
  gui:
    restart: unless-stopped
    build:
      context: ./gui
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - CONFIGURATION=${GUI_CONFIGURATION}
    depends_on:
      server:
        condition: service_started
        restart: true
    environment:
      - SERVER_API_URL=http://server/api/
    ports:
      - ${PORT}:80

  server:
    restart: unless-stopped
    build:
      context: ./server
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - "file-store:/borg/file-store"
      - "./config:/borg/config"
    environment:
      - GIN_MODE=${GIN_MODE}

  droid:
    restart: unless-stopped
    build:
      context: ./tools/droid
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - "file-store:/borg/file-store"
    environment:
      - GIN_MODE=${GIN_MODE}

  tika:
    restart: unless-stopped
    build:
      context: ./tools/tika
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - "file-store:/borg/file-store"
    environment:
      - GIN_MODE=${GIN_MODE}

  jhove:
    restart: unless-stopped
    build:
      context: ./tools/jhove
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - "file-store:/borg/file-store"
    environment:
      - GIN_MODE=${GIN_MODE}

  verapdf:
    restart: unless-stopped
    build:
      context: ./tools/verapdf
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - "file-store:/borg/file-store"
    environment:
      - GIN_MODE=${GIN_MODE}

  odf-validator:
    restart: unless-stopped
    build:
      context: ./tools/odf-validator
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - "file-store:/borg/file-store"
    environment:
      - GIN_MODE=${GIN_MODE}

  ooxml-validator:
    restart: unless-stopped
    build:
      context: ./tools/ooxml-validator
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - "file-store:/borg/file-store"
    environment:
      - GIN_MODE=${GIN_MODE}

volumes:
  file-store:
