services:
  server:
    container_name: borg-server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: dockerfile_server
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - "filestore:/borg/filestore"
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - BORG_SERVER_CONTAINER_PORT=${BORG_SERVER_CONTAINER_PORT}
    ports:
      - ${BORG_SERVER_HOST_PORT}:${BORG_SERVER_CONTAINER_PORT}
  droid-api:
    container_name: droid-api
    restart: unless-stopped
    build:
      context: ./tools/droid
      dockerfile: dockerfile_droid
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - "filestore:/borg/filestore"
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - DROID_API_CONTAINER_PORT=${DROID_API_CONTAINER_PORT}
    ports:
      - ${DROID_API_HOST_PORT}:${DROID_API_CONTAINER_PORT}

volumes:
  filestore: