services:

  server:
    container_name: borg-server
    restart: unless-stopped
    build:
      context: ./server
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - "filestore:/borg/filestore"
    ports:
      - ${BORG_SERVER_HOST_PORT}:80

  droid-api:
    container_name: droid-api
    restart: unless-stopped
    build:
      context: ./tools/droid
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - "filestore:/borg/filestore"

  tika-api:
    container_name: tika-api
    restart: unless-stopped
    build:
      context: ./tools/tika
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - "filestore:/borg/filestore"

  jhove-api:
    container_name: jhove-api
    restart: unless-stopped
    build:
      context: ./tools/jhove
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - "filestore:/borg/filestore"

  verapdf-api:
    container_name: verapdf-api
    restart: unless-stopped
    build:
      context: ./tools/verapdf
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - "filestore:/borg/filestore"

volumes:
  filestore: