formatIdentificationTools:
  - 
    toolName: "DROID"
    toolVersion: "6.7.0"
    endpoint: "http://droid-api:3000/identify-file-format"
    features:
      -
        key: "puid"
        confidence:
          defaultValue: 1.0
  -
    toolName: "Tika"
    toolVersion: "2.9.0"
    endpoint: "http://tika-api:3000/extract-metadata"
    features:
      -
        key: "mimeType"
        confidence:
          defaultValue: 1.0
      -
        key: "encoding"
        confidence:
          defaultValue: 1.0
      -
        key: "size"
        confidence:
          defaultValue: 1.0
      -
        key: "formatVersion"
        confidence:
          defaultValue: 1.0
      -
        key: "pdfaVersion"
        confidence:
          defaultValue: 1.0

formatValidationTools:
  -
    toolName: "JHOVE - PDF Modul"
    toolVersion: "1.28.0"
    endpoint: "http://jhove-api:3000/validate/pdf"
    trigger:
      -
        feature: "mimeType"
        regEx: "pdf"
    features:
      -
        key: "wellFormed"
        confidence:
          defaultValue: 1.0
      -
        key: "valid"
        confidence:
          defaultValue: 1.0
      # ignore until a identification tool extracts the format name also
      # -
      #   key: "formatName"
      #   confidence:
      #     defaultValue: 0.8
      -
        key: "formatVersion"
        confidence:
          defaultValue: 0.8
