formatIdentificationTools:
  - 
    toolName: "DROID"
    toolVersion: "6.7.0"
    endpoint: "http://droid-api:3000/identify-file-format"
  -
    toolName: "Tika"
    toolVersion: "2.9.0"
    endpoint: "http://tika-api:3000/extract-metadata"