FROM golang:alpine AS build
WORKDIR /borg/tools/jhove
COPY . ./
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o jhove_api cmd/jhove-api.go

FROM alpine:3.18 AS prod
WORKDIR /borg/tools/jhove
COPY --from=build /borg/tools/jhove/ .
RUN apk update
RUN apk add openjdk17
CMD ["./jhove_api"]