FROM golang:alpine AS build
WORKDIR /borg/tools/jhove
COPY . ./
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o jhove_api cmd/jhove_api.go

FROM alpine:3.18 AS prod
WORKDIR /borg/tools/jhove
COPY --from=build /borg/tools/jhove/ .
RUN apk update
RUN apk add openjdk17
# install JHOVE with jar, enter sequence of characters required for the installation wizard
RUN sh -c '/bin/echo -e "1\njhove\nO\n1\nY\n1" | java -jar bin/jhove_1.28.0.jar'
CMD ["./jhove_api"]