FROM golang:alpine AS build
WORKDIR /borg/tools/tika
COPY . ./
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o tika_api cmd/tika-api.go

FROM alpine:3.18 AS prod
WORKDIR /borg/tools/tika
COPY --from=build /borg/tools/tika/ .
RUN apk update
RUN apk add openjdk17
CMD ["./tika_api"]